version: '2'
services:

  server-starter:
    build: ./src
    restart: always
    environment:
      - NODE_ENV=production
      - MONGODB=mongodb://mongodb/server-starter
      - PORT=3100
      - DIGEST_NAME=sha256
      - SECRET_KEY=SERVER_STARTER
    ports:
        - 3100:3100
    links:
        - mongodb

  mongodb:
    image: mongo:latest
    environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
    volumes:
        - ./data/db:/data/db
    expose:
        - 27017