version: '2'
services:

  taxi_backend:
    build: ./src
    restart: always
    environment:
      - NODE_ENV=production
      - MONGODB=mongodb://mongodb/taxi_backend
      - PORT=3100
      - DIGEST_NAME=sha256
      - SECRET_KEY=SERVER_STARTER
    expose:
      - 8084
    links:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
    volumes:
        - ./data/db:/data/db
    expose:
        - 27017